### ISSUE TITLE
Version 4 upgrade

### ISSUE THREAD

**Issue by SkeLLLa** [seppevs/migrate-mongo#29]
Hi. I've noticed that new version is published. However there are no changelog there. Could you please describe what's changed since 3.0.5 and is it safe to upgrade or there were some breaking changes?

**Comment by seppevs** [comment]
Hi. Sorry, for not providing a changelog. I will do this from now on when I bump the major version.

There is 1 breaking change: the filename of the config is changed from `config.js` to `migrate-mongo-config.js`. So if you upgrade to 4.x.x, you will need to rename your config file to `migrate-mongo-config.js`.

I also rewrote most of the code so it uses async & await instead of callbacks. But as a user, there shouldn't be any impact.
