### ISSUE TITLE
Command line parameter for custom config file

### ISSUE THREAD

**Issue by vinhtq** [seppevs/migrate-mongo#3]
Currently we use config.js as default option. Can we allow people to use their custom config file name?

Thank you!

**Comment by seppevs** [comment]
Since the config.js file is loaded with Node's `require`, you are free to do what you want in this file in order to resolve the config parameters migrate-mongo needs. You can even make use of a `package.json` file and use any npm module you want.

The only requirement is that the config.js returns an object that contains a 'mongodb' attribute with an 'url'. For example:
```
  mongodb: {
    url: 'mongodb://192.168.20.30:27017/albums'
  }
```

It doesn't matter how you retrieved this url. You can hardcode it in the config.js file or resolve it through a database, environment variable, etc ..

## One possibility is to work with an environment variable
This is, more or less, how we make use of custom config files at our company.

### config.js:
```
const path = require('path');
const configFileName = process.env.MIGRATE_MONGO_CONFIG_FILENAME;
module.exports = require(path.join(__dirname, configFileName);
```

### local-config.js:
```
'use strict';

// This is where you can configure migrate-mongo
module.exports = {

  // The mongodb collection where the applied changes are stored:
  changelogCollectionName: 'changelog',

  mongodb: {
    // TODO edit this connection url to your MongoDB database:
    url: 'mongodb://localhost:27017/YOURDATABASENAME' 
  }
};
```

### To run it:
`$ MIGRATE_MONGO_CONFIG_FILENAME=local-config.js migrate-mongo status`

Does this answers your question?

**Comment by vinhtq** [comment]
Great! Thank you

**Comment by smolyakoff** [comment]
> Since the config.js file is loaded with Node's require, you are free to do what you want in this file in order to resolve the config parameters migrate-mongo needs

Nice, but it won't help you if you have a config directory or config.js file in the root of your project which is dedicated for other purposes like. It would be great to have an ability to specify custom config file location and migrations directory as well

**Comment by seppevs** [comment]
I my experience, it works better to have your migrations + their database config isolated from the rest of your project(s). I usually create a dedicated 'migrations' project for each mongodb database.

BUT, if you really want, you can 'require' your actual config file with a relative path or use an environment variable. Changing the location of the 'migrations' directory is currently not possible.

**Comment by smolyakoff** [comment]
> BUT, if you really want, you can 'require' your actual config file with a relative path or use an environment variable.

What I really want is to have a config folder with my ordinary config and `migrations-config.js` file for migrations. So the project structure looks like this in the end:

```
project/
  migrations/
    20160101010101-migration-one.js
    20160101010101-migration-two.js
  config/
    index.js
    default.json
    production.json
  migrations-config.js
  package.json
```

`migrations-config` can require my ordinary config and expose required variables for the `migrate-mongo`.

It's not possible with your library at the moment.

**Comment by seppevs** [comment]
It's possible, but you'll have to rename your `migrations-config.js` to `config.js`

**Comment by smolyakoff** [comment]
> It's possible, but you'll have to rename your migrations-config.js to config.js
It's confusing to have both `config` directory and `config.js` file at the same level. `require('./config')` will be misleading

**Comment by smolyakoff** [comment]
Imagine how many libraries in npm could use `config.js` as configuration file. That's why every library use its own specific name and allows to override it, see `webpack.config.js` or `.eslint.json` or any other popular library

**Comment by davidmat** [comment]
+1

**Comment by seppevs** [comment]
I will look into it.

**Comment by seppevs** [comment]
Since version v1.2.1 it's possible to provide a path to a custom config file to the `status`, `up` and `down` actions.
For `init` and `create`, it's not necessary because these actions don't use the config file at all.

See the README.md file for an example (or use the `-h` option on any of these actions)
