### ISSUE TITLE
Hidden breaking change in latest patch

### ISSUE THREAD

**Issue by Parnswir** [seppevs/migrate-mongo#392]
The latest patch version of this library contains a major update of the `mongodb` package. This can lead to breaking migrations, for instance when using mongoose within the migrations.

**To Reproduce**
1. `npm i migrate-monog@8.2.2 mongoose@latest`
2. create a migration and follow the [transaction guide](https://github.com/seppevs/migrate-mongo#using-mongodbs-transactions-api); use the mongoose transaction helper
3. Migration works 🙂
4. `npm i migrate-monog@8.2.3`
5. Migration fails 😶 (because mongoose thinks a mongodb v4 MongoClient is not a MongoClient)

**Expected behavior**
I wouldn't have expected a major dependency update in a patch release. A changelog file would be nice 🤗

**Comment by GlennGeenen** [comment]
We experienced the same with a MongoParseError, our migrations broke updating to 8.2.3. We're now fixed on version 8.2.2.

Nevertheless, thank you for your work, super helpful!!!

**Comment by DjebbZ** [comment]
Other breaking change: the type definition that comes with the major update of `mongodb` in 8.2.3 make our migration code not compile because the type of a path in `$addToSet` is now `never` instead of `string` (!?) or something like that. Fixed on version 8.2.2, haven't nailed down the underlying change exactly.
